export const DEFAULT_PAGE = 1;
export const DEFAULT_PAGE_SIZE = 10;
export const MAX_PAGE_SIZE = 100;
export const ROOM_BONUS_POINTS = 50;
export const ROOM_MESSAGE_RATE_LIMIT = 10;
export const ROOM_MESSAGE_RATE_WINDOW_MS = 10_000;
export const ROOM_CREATE_RATE_LIMIT = 5;
export const ROOM_CREATE_RATE_WINDOW_MS = 60 * 60 * 1000;
export const ROOM_MESSAGE_PAGE_SIZE = 50;
export const ROOM_SLOTS_PAGE_SIZE = 50;
export const ROOM_STALE_AFTER_MS = 3 * 24 * 60 * 60 * 1000;
export const QUIZ_QUESTIONS_PER_ATTEMPT = 8; // ~3-4 min per open-ended answer ≈ 30 min
export const QUIZ_DURATION_MS = 30 * 60 * 1000;
export const QUIZ_INITIAL_BANK_SIZE = 15;
export const QUIZ_TOPUP_COUNT = 10;
export const QUIZ_TOPUP_THRESHOLD = QUIZ_QUESTIONS_PER_ATTEMPT * 2;
